### ISSUE TITLE
Can you share how to train? Is four datasets not enough?

### ISSUE THREAD

**Issue by Originlightwkp** [aimagelab/open-fashion-clip#1]
very thanks!

**Comment by giuseppecartella** [comment]
Hi @Originlightwkp ,

Thanks for the interest in our work!
For the moment we do not plan to release the training code.

However, the procedure is quite simple. 
You should download all the training datasets mentioned in the paper and create a dataloader merging all of them. 
You can instantiate the model by using open clip implementation (https://github.com/mlfoundations/open_clip).

Giuseppe
