### ISSUE TITLE
permission denial for downloading weights

### ISSUE THREAD

**Issue by hmd78** [aimagelab/open-fashion-clip#2]
first of all thank you for your great work.
I used to test and work with your repo. I previously used weights without any problem but now I get " Forbidden You don't have permission to access this resource." error when i wanted to download weights from the provided link :

https://ailb-web.ing.unimore.it/publicfiles/OpenFashionCLIP/finetuned_clip.pt

**Comment by marcellacornia** [comment]
Hi @hmd78, 
thanks for your interest in our work.

The download link should work now. Sorry for the inconvenience.

**Comment by lazyhope** [comment]
@marcellacornia Hi! Thanks for the great work! The link is not working again, maybe consider uploading them to HuggingFace Hub?

Edit: It is working now, thanks a lot!
