### ISSUE TITLE
The weights can't be downloaded?

### ISSUE THREAD

**Issue by wendashi** [aimagelab/open-fashion-clip#3]
![image](https://github.com/aimagelab/open-fashion-clip/assets/141135497/8924de76-e039-4660-a82c-ea109b1adc54)

When I click this link, it's forbidden.

![image](https://github.com/aimagelab/open-fashion-clip/assets/141135497/3220599e-2ca0-4fdf-846c-ec376c890303)

**Comment by marcellacornia** [comment]
Hi @wendashi,
The download link should work now. Sorry for the inconvenience.

**Comment by syna-nalinear** [comment]
Hello @marcellacornia , Thank you for your excellent repository!
I'm posting this comment as it has recurred. Please help T_T

**Comment by giuseppecartella** [comment]
Hi @syna-nalinear . I tried and I managed to download the checkpoint with success. It should be available. Just let me know if you still have the problem.

**Comment by syna-nalinear** [comment]
@giuseppecartella 
Thank you for your response. I believe the issue was related to my internet environment at the time, such as the firewall settings. The issue has now been resolved!
